[tool.poetry]
name = "live_pybins"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Cython = "^0.29.24"
pyoxidizer = "^0.16.2"
pyarmor = "^6.7.3"
pyinstaller = "^4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
