[tool.poetry]
name = "live210"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.5"
Pyrogram = "^2.0.30"
python-dotenv = "^0.20.0"
TgCrypto = "^1.2.3"
uvloop = "^0.16.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
