version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-live"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dy4os2vdyf92"
s3_prefix = "sam-live"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
